/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#231b00",
        "secondary": "#725c00",
        "on-primary-container": "#bbc5ff",
        "inverse-surface": "#303035",
        "primary": "#002da5",
        "primary-fixed-dim": "#b8c3ff",
        "surface": "#fbf8ff",
        "on-secondary-fixed-variant": "#564500",
        "surface-dim": "#d9d9e6",
        "accent-orange": "#ffdad6",
        "surface-container-low": "#f5f2f9",
        "secondary-fixed-dim": "#ebc22e",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#f5b8c3",
        "on-secondary-container": "#715b00",
        "outline": "#747687",
        "on-tertiary-fixed": "#331019",
        "cream-bg": "#fbf8ff",
        "on-tertiary": "#ffffff",
        "surface-container": "#efedf4",
        "tertiary-container": "#754650",
        "inverse-primary": "#b8c3ff",
        "tertiary": "#5a3039",
        "primary-fixed": "#dde1ff",
        "secondary-container": "#fdd33f",
        "on-background": "#1b1b20",
        "accent-pink": "#ffd9df",
        "secondary-fixed": "#ffe082",
        "primary-container": "#003fdd",
        "outline-variant": "#c4c5d8",
        "background": "#fbf8ff",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1b20",
        "on-error-container": "#93000a",
        "surface-bright": "#fbf8ff",
        "surface-variant": "#e4e1e8",
        "on-surface-variant": "#434655",
        "inverse-on-surface": "#f2eff6",
        "on-error": "#ffffff",
        "ink-black": "#1A1A1A",
        "on-tertiary-fixed-variant": "#663a43",
        "tertiary-fixed-dim": "#f4b6c1",
        "surface-container-high": "#eae7ee",
        "accent-sage": "#d9d9e6",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffd9df",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e4e1e8",
        "on-primary-fixed-variant": "#0035be",
        "on-primary-fixed": "#001356",
        "surface-tint": "#1d4ce8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        "container-padding": "32px",
        "stack-lg": "48px",
        base: "8px",
        "stack-sm": "12px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        "stack-md": "24px"
      },
      fontFamily: {
        "label-bold": ["DM Sans", "sans-serif"],
        "display-lg-mobile": ["Lexend", "sans-serif"],
        "display-lg": ["Lexend", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "headline-md": ["Lexend", "sans-serif"],
        "headline-sm": ["Lexend", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"]
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
