
services:
  postgres:
    image: postgres:15-alpine
    container_name: sarvuday_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: survuday
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:8.0
    container_name: sarvuday_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: survuday
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db



volumes:
  postgres_data:
  mongo_data:

