services:
  - type: web
    name: sarvuday-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: MONGO_DB_USERNAME
        sync: false
      - key: MONGO_DB_PASSWORD
        sync: false

      - key: FRONTEND_BASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: '1440'
      - key: RESET_TOKEN_EXPIRE_MINUTES
        value: '10'
      - key: EMAIL_RESEND_RATE_LIMIT_MINUTES
        value: '10'
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: CHATBOT_BASE_URL
        sync: false
      - key: CHATBOT_API_KEY
        sync: false
      - key: CHATBOT_MODEL
        sync: false
      - key: CHATBOT_TEMPERATURE
        value: '0.8'
      - key: MAX_TOTAL_TOKENS
        value: '2048'
      - key: DAILY_BASE_URL
        value: https://api.daily.co/v1
      - key: DAILY_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
