/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#434655",
        "surface-container-high": "#eae7ee",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed": "#231b00",
        "secondary-fixed-dim": "#ebc22e",
        "on-tertiary-fixed": "#331019",
        "inverse-on-surface": "#f2eff6",
        "primary": "#002da5",
        "surface-dim": "#d9d9e6",
        "tertiary-fixed": "#ffd9df",
        "on-tertiary-fixed-variant": "#663a43",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b8c3ff",
        "on-error": "#ffffff",
        "ink-black": "#1A1A1A",
        "on-surface": "#1b1b20",
        "accent-pink": "#ffd9df",
        "secondary-container": "#fdd33f",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "outline-variant": "#c4c5d8",
        "on-primary-fixed-variant": "#0035be",
        "inverse-primary": "#b8c3ff",
        "surface-container": "#efedf4",
        "on-background": "#1b1b20",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e1e8",
        "accent-orange": "#ffdad6",
        "on-primary-fixed": "#001356",
        "on-tertiary": "#ffffff",
        "outline": "#747687",
        "tertiary-fixed-dim": "#f4b6c1",
        "surface-tint": "#1d4ce8",
        "on-primary-container": "#bbc5ff",
        "background": "#fbf8ff",
        "on-secondary": "#ffffff",
        "primary-container": "#003fdd",
        "tertiary": "#5a3039",
        "on-tertiary-container": "#f5b8c3",
        "accent-sage": "#d9d9e6",
        "secondary": "#725c00",
        "tertiary-container": "#754650",
        "surface-container-highest": "#e4e1e8",
        "surface": "#fbf8ff",
        "secondary-fixed": "#ffe082",
        "surface-container-low": "#f5f2f9",
        "inverse-surface": "#303035",
        "on-secondary-fixed-variant": "#564500",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#715b00",
        "surface-bright": "#fbf8ff",
        "cream-bg": "#fbf8ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "24px",
        "margin-mobile": "20px",
        "stack-lg": "48px",
        "container-padding": "32px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "base": "8px",
        "stack-sm": "12px"
      }
    },
  },
  plugins: [],
}
